#Dependencies
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Mike Littlefield 
tagline:	  github.com/mikstelit
paginate:         1
author:
  name:           Mike Littlefield 
  url:            https://mikstelit.github.io
  email:          mike.littlefield@live.com 

# Custom vars
version:          1.0.0
github:           
repo:             https://github.com/mikstelit/miksteli.github.io
