# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Mike Littlefield
url:              http://192.168.0.156:4000
paginate:         1
author:
  name:          Mike Littlefield 

# GitHub Configuration Options
safe: true
lsi: false

# Custom vars
version:          1.0.0
